---

- hosts: vars.yml
  name: Setup Debian for Python and Docker
  gather_facts: false
  become: True
  become_user: root
  vars:
    standard_user: pk_azure # FIXME: PUT INTO ANSIBLE VAULT!

  tasks:
    - name: Update and Install Packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full
        autoclean: yes
        autoremove: yes
        install_recommends: yes
        name:
          pkg:
            - docker.io=
            - docker-compose=
            - sqlite3=
#    - name: Download and Install Docker-Ce
#      - https://github.com/docker/docker-ce/archive/refs/tags/v19.03.15.tar.gz
    - name: Download and Install Docker-Compose
      vars:
        - compose_version: v2.2.3
        - os: linux
        - arch: x86_64
        - source_url: https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ os }}-{{ arch }}
        ansible.builtin.copy:
          src: source_url
          dst: /usr/local/bin/docker-compose
          owner: {{ standard_user }} # TODO: I CZY TO
          mode: "0700" # TODO: CZY DZIALA TO
    - name: Download Dependencies for building Python
      ansible.builtin.apt:
        # TODO: ADD STUFF
        - name:
            - pkg:
                - uuid-dev
                - libssl-dev
                - libreadline-dev
                - zlib1g-dev
                - libsqlite3-dev
                - liblzma-dev
                - libncurses5-dev
                - libbz2-dev
                - libgdbm-dev
    - name: Download and unarchive Python Source Code
      vars:
        - source_url: https://www.python.org/ftp/python/3.10.2/Python-3.10.2.tgz
        - source_checksum: 67c92270be6701f4a6fed57c4530139b
      ansible.builtin.get_url:
#        - dist: /tmp/ # FIXME?
        dist: /tmp/Python3.10.2.tgz
        url: {{ source_url }}
        checksum: md5:{{ source_checksum }}
#        - mode: "" # FIXME
      ansible.builtin.unarchive:
        src: /tmp/Python3.10.2.tgz #
        dest: /tmp/
    - name: Install Python
      community.general.make:
        chdir: /tmp/Python3.10.2 # FIXME VARIABLE
        target:
    - name: Setup Env Variables
    - name: Copy SSH key
      anisble.builtin.copy:
        src:
        dest: /home/{{ azure_user }}/.ssh/
        owner: {{ azure_user }}
#        group: {{ azure_group }}
        mode: '0400'

