# Generated by Django 4.0.2 on 2022-02-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(max_length=250)),
                ('title', models.TextField()),
                ('full_title', models.TextField()),
                ('year', models.TextField()),
                ('image_url', models.TextField()),
                ('crew', models.TextField()),
                ('imbd_rating', models.FloatField()),
                ('imbd_rating_count', models.PositiveIntegerField()),
            ],
        ),
    ]
